### Create a New Order
POST http://localhost:3000/api/orders/create-order
Content-Type: application/json

{
    "userId": "36B35840-8B83-4327-AD3F-6CA0C8323F9C",
    "productId": "e070174e-992d-4e0c-af63-17d6384eb0e6",
    "quantity": "10"
}

### Update an Order
PUT http://localhost:3000/api/orders/5eacf47a-d0fe-4b70-979f-8ff695db9ab2
Content-Type: application/json

{
    "quantity": "3"
}

### Delete an Order
DELETE http://localhost:3000/api/orders/5eacf47a-d0fe-4b70-979f-8ff695db9ab2

### Get All Orders
GET http://localhost:3000/api/orders

### Get Order by ID
GET http://localhost:3000/api/orders/5eacf47a-d0fe-4b70-979f-8ff695db9ab2
