### Create a New Product
POST http://localhost:3000/api/products/create-product
Content-Type: application/json

{
    "name": "Viennesse Iced Coffee",
    "short_description": "Vienna coffee is a delightful treat for coffee lovers. This coffee drink is typically prepared with a double espresso and topped with whisked whipped cream, then dusted with cocoa powder or chocolate shavings.",
    "price": "5.00",
    "image": "https://i.pinimg.com/474x/b5/ec/65/b5ec650bd79c564223bbffc0a52b31f6.jpg",
    "category": "Dessert",
    "stock": "30",
    "flavor": "Vienna Latte"
}

### Update a Product
PUT http://localhost:3000/api/products/9658a776-7970-4157-b3e5-974f8f5cd3c8
Content-Type: application/json

{
    "name": "Espresso",
    "short_description": "A strong concentrated coffee drink typically served in a small espresso cup.",
    "price": "6.50",
    "image": "https://i.pinimg.com/474x/a8/c3/30/a8c330fd5cced864f4b300c7afabdd40.jpg",
    "category": "Espresso",
    "stock": "70",
    "flavor": "vanilla"
}

### Delete a Product
DELETE http://localhost:3000/api/products/b3423c9d-bd30-4fb0-8b6c-bd02e6418b22

### Get All Products
GET http://localhost:3000/api/products

### Get Product by ID
GET http://localhost:3000/api/products/dd791e8e-f682-404d-bbf4-1a8274129c7e
