### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "  Whitney",
  "lastname": "Navalia",
  "phoneNumber": "0111997934",
  "address": "Chuka",
  "email": "whitney@example.com",
  "password": "password123"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

### Update User
PUT http://localhost:3000/api/users/F6C89196-799B-4D45-A4D1-8B1657C10069
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "phoneNumber": "123456789",
  "address": "dfghj",
  "email": "dfghjk@example.com",
  "password": "edrfghjk"

}

### Delete User
DELETE http://localhost:3000/api/users/A121D48B-F423-44CA-8547-52B13B15B9FE

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/BBFF8072-B5A3-47B1-9BC1-AD206C5995BC
