### Register User
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "firstname": "Stanleyasdfg",
  "lastname": "Nyakinda",
  "phoneNumber": "0740837666",
  "address": "Chuka",
  "email": "stanleyghj@example.com",
  "password": "password123"
}

### Login User ( admin )
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "adminpassword"
}

### Login User ( user )
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "whitney@example.com",
  "password": "password123"
}

### Update User
PUT http://localhost:3000/api/users/BBFF8072-B5A3-47B1-9BC1-AD206C5995BC
Content-Type: application/json

{
  "firstname": "Stanleywer",
  "lastname": "Nyakinda",
  "phoneNumber": "0740837669",
  "address": "Chuka",
  "email": "stanleywer@example.com",
  "password": "password123"
}

### Delete User
DELETE http://localhost:3000/api/users/CD342760-9351-4023-BD12-2CA996CCE263

### Get All Users
GET http://localhost:3000/api/users

### Get User by ID
GET http://localhost:3000/api/users/CD342760-9351-4023-BD12-2CA996CCE263

